# Generated by Django 5.2.6 on 2025-10-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ANALYST', 'Analyst'), ('SUPERVISOR', 'Supervisor'), ('MANAGER', 'Manager'), ('CHIEF_MANAGER', 'Chief Manager'), ('ADMIN', 'Admin')], default='USER', max_length=20),
        ),
    ]
