# Generated by Django 5.2.6 on 2025-09-09 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuals', to='api.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_manuals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ManualVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('changelog', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_html', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_versions', to=settings.AUTH_USER_MODEL)),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.manual')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='manual',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_manuals', to='api.manualversion'),
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('TABLE', 'Table'), ('CHECKLIST', 'Checklist'), ('DIAGRAM', 'Diagram'), ('TABS', 'Tabs')], max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='api.manualversion')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('PUBLISH', 'Publish'), ('ROLLBACK', 'Rollback')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('manual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.manual')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.manualversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_reviews', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='api.manualversion')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='manual',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='manuals', to='api.tag'),
        ),
        migrations.AddIndex(
            model_name='manualversion',
            index=models.Index(fields=['manual', 'version_number'], name='api_manualv_manual__b5dcc7_idx'),
        ),
        migrations.AddIndex(
            model_name='manualversion',
            index=models.Index(fields=['is_published'], name='api_manualv_is_publ_74d189_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='manualversion',
            unique_together={('manual', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='contentblock',
            index=models.Index(fields=['version', 'order'], name='api_content_version_b297ad_idx'),
        ),
        migrations.AddIndex(
            model_name='contentblock',
            index=models.Index(fields=['type'], name='api_content_type_164e45_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='api_auditlo_action_0a1743_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='api_auditlo_created_ec4a64_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewrequest',
            index=models.Index(fields=['status'], name='api_reviewr_status_a074f0_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewrequest',
            index=models.Index(fields=['submitted_at'], name='api_reviewr_submitt_94f9f9_idx'),
        ),
        migrations.AddIndex(
            model_name='manual',
            index=models.Index(fields=['slug'], name='api_manual_slug_4b187d_idx'),
        ),
        migrations.AddIndex(
            model_name='manual',
            index=models.Index(fields=['status'], name='api_manual_status_3a4da9_idx'),
        ),
        migrations.AddIndex(
            model_name='manual',
            index=models.Index(fields=['department'], name='api_manual_departm_c2050b_idx'),
        ),
    ]
