# Generated by Django 5.2.6 on 2025-10-02 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_manualcollaborator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True),
        ),
        migrations.AddIndex(
            model_name='manual',
            index=models.Index(fields=['reference'], name='api_manual_referen_d524a4_idx'),
        ),
    ]
