# Generated by Django 5.2.6 on 2025-10-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_manual_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('TABLE', 'Table'), ('LIST', 'List'), ('CODE', 'Code'), ('QUOTE', 'Quote'), ('DIVIDER', 'Divider'), ('CHECKLIST', 'Checklist'), ('DIAGRAM', 'Diagram'), ('TABS', 'Tabs')], max_length=20),
        ),
    ]
